# Generated by Django 4.2.7 on 2023-11-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contact_date_and_time_contact_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_and_time',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='type',
        ),
    ]
